### ISSUE TITLE
Cannot import defusedxml ElementTree and/or xmlrpc

### ISSUE THREAD

**Issue by StephaneGerardVUB** [EGI-Foundation/cloud-info-provider#62]
Hello, I have tested version 0.8.3-1.el6, and it gives the following error messages :

[root@rocci ~]# /var/lib/bdii/gip/provider/cloud-info-provider
Traceback (most recent call last):
  File "/usr/bin/cloud-info-provider-service", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.6/site-packages/cloud_info/core.py", line 204, in main
    bdii = cls_(opts)
  File "/usr/lib/python2.6/site-packages/cloud_info/core.py", line 124, in __init__
    super(CloudBDII, self).__init__(opts)
  File "/usr/lib/python2.6/site-packages/cloud_info/core.py", line 28, in __init__
    self.dynamic_provider = SUPPORTED_MIDDLEWARE[opts.middleware](opts)
  File "/usr/lib/python2.6/site-packages/cloud_info/providers/opennebula.py", line 257, in __init__
    super(OpenNebulaROCCIProvider, self).__init__(opts)
  File "/usr/lib/python2.6/site-packages/cloud_info/providers/opennebula.py", line 22, in __init__
    raise exceptions.OpenNebulaProviderException(msg)
cloud_info.exceptions.OpenNebulaProviderException: Cannot import defusedxml ElementTree and/or xmlrpc.

Regards

**Comment by StephaneGerardVUB** [comment]
Problem fiixed after installing python-defusedxml.noarch. This should be a dependency of the cloud-info-provider RPM

**Comment by arax** [comment]
We are discussing this issue in #61 right now.

**Comment by gwarf** [comment]
Hi @StephaneGerardVUB

Yes defusedxml is a dependency and is not included in a dependency list as it is not in the default repository and it is only needed for OpenNebula and not for OpenStack nor Synnefo and as currently there is one package for all and we don't want people to have to install one pacakge they do not need, especially if it is in an external/additional repo.

As @arax said we are discussing how we want to handle this in #61 Please raise your voice if you want.

**Comment by gwarf** [comment]
Moved to #63
